### ISSUE TITLE
Error, invalid structure

### ISSUE THREAD

**Issue by NickBolles** [clinton-hall/CP-BackupTool#26]
```
Traceback (most recent call last):
  File "wanted.py", line 180, in <module> process(args.type, args.file)
  File "wanted.py", line 112, in process movie_list.append(item["info"]["imdb"])
KeyError: 'info'
```
One of the inputs in the movies array is:
```
    {
      "_t": "property",
      "releases": null,
      "_rev": "007ce6d6",
      "profile_id": "973a24eb55fb4abda8904c3f03640102",
      "value": "1459147987.37",
      "_id": "6f863e54469940abb9140ddb9fe24ac9",
      "identifier": "last_ignored_eta.6f863e54469940abb9140ddb9fe24ac9"
    }
```
I fixed it by adding: on line 106
```
                if item["_t"] == "property":
                    continue;
```

**Comment by peerster** [comment]
I think the solution is to check for the info key instead, otherwise skip that item. Will look at the code when I have time

**Comment by clinton-hall** [comment]
please let me know if this works ok...

**Comment by NickBolles** [comment]
LGTM
