### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by henkjanvries** [clinton-hall/CP-BackupTool#27]
Im getting the following error when running the script:

`Traceback (most recent call last):
  File "./wanted.py", line 182, in <module>
    process(args.type, args.file)
  File "./wanted.py", line 100, in process
    result = listWanted(baseurl)
  File "./wanted.py", line 64, in listWanted
    result = apiCall(url)
  File "./wanted.py", line 55, in apiCall
    result = json.load(urlObj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

Do you have a fix for this problem?

**Comment by clinton-hall** [comment]
I just tested and this error happens if you don't have the couchpotato api key in the couch.cfg file, or otherwise run this with the `--cfg /your/path/.couchpotato/settings.conf` argument.
